### ISSUE TITLE
Could not parse error 

### ISSUE THREAD

**Issue by Gabo-Nane** [CyberPunkMetalHead/Binance-News-Sentiment-Bot#19]
When running the code, the headlines of some pages are not being parsed (like 37/103 pages are actually being parced)
the error says:
"Could not parse "www.examplepage.com/feed" error is: "
(doesn't say what the error is, it just says there's an error)

![Could not parse error](https://user-images.githubusercontent.com/82825027/115287086-daafa600-a11d-11eb-9c41-bdc2727e4f8f.png)

When i click those links i just see some code, i tried openning the pages in different browsers but always return code.

![page](https://user-images.githubusercontent.com/82825027/115287548-6aedeb00-a11e-11eb-8d23-a6330d606044.png)

(sorry for writing this here but idk if this is against any /r/bitcoin rules)

**Comment by idanpl** [comment]
I think that the timeout given was simply to small (7 seconds).
I increased the timeout on my local computer to 60 seconds, and many articles could not be parsed.

**Comment by idanpl** [comment]
sending a pull request.
