### ISSUE TITLE
Exclude articles after defined time has past

### ISSUE THREAD

**Issue by adteague** [CyberPunkMetalHead/Binance-News-Sentiment-Bot#24]
Here's how I implemented it:
Add `timezone` to `datetime` import
```
# define how old an article can be to be included
# in hours
HOURS_PAST = 24
```
```
# convert pubDat to datetime
published = datetime.strptime(pubDate.replace("GMT", "+0000"), '%a, %d %b %Y %H:%M:%S %z')
# calculate timedelta
time_between = datetime.now(timezone.utc) - published

if (time_between.total_seconds() / (60 * 60) <= HOURS_PAST):
```
Add ^ before the following...
https://github.com/CyberPunkMetalHead/Binance-News-Sentiment-Bot/blob/56da3d171a77d2b6a574ba63cbae0887eaa3b2e8/news-analysis.py#L224-L230

**Comment by adteague** [comment]
I implemented this because I noticed an article from May 2020 was being included in the sentiment analysis 😄  Thanks for the great code to build off of!

**Comment by CyberPunkMetalHead** [comment]
This is a good idea, thanks for pointing that out! Feel free to create a pull request for the latest commit.

**Comment by CyberPunkMetalHead** [comment]
This has now been merged to main in the last commit!
