### ISSUE TITLE
sleeping time

### ISSUE THREAD

**Issue by Waruid** [CyberPunkMetalHead/Binance-News-Sentiment-Bot#29]
Hi, thank you for providing this code! I realize you said the script is running every 60 minute in reddit but in coding time.sleep()is taking 60 seconds right now. Is this intended to run script every 60 seconds for testing?

**Comment by CyberPunkMetalHead** [comment]
Hi there, good point - I have used this for testing but didn't mean to leave it in there. I have now adjusted the code to run once very hour by default.
