### ISSUE TITLE
vader_lexicon issue?

### ISSUE THREAD

**Issue by Ozeitis** [CyberPunkMetalHead/Binance-News-Sentiment-Bot#31]
**********************************************************************
  Resource vader_lexicon not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('vader_lexicon')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load sentiment/vader_lexicon.zip/vader_lexicon/vader_lexicon.txt

  Searched in:
    - '/root/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************

**Comment by Ozeitis** [comment]
I get this upon loading the bot. I dont see what happened

**Comment by CyberPunkMetalHead** [comment]
Can you try running nltk.download() once and then run the script?

**Comment by Ozeitis** [comment]
> Can you try running nltk.download() once and then run the script?

I added it to the code and now that error is gone but I have another I am trying to deal with :D thanks!

**Comment by JanHadari** [comment]
Uppppp
