### ISSUE TITLE
'could not parse' error

### ISSUE THREAD

**Issue by simin75simin** [CyberPunkMetalHead/Binance-News-Sentiment-Bot#32]
an example would be:
```Could not parse https://www.coin.space/feed/ error is:```
this happened on google colab, and my own machine (ubuntu 18.04, python3.7.10). most of the news source it cannot parse at this moment, which is kinda worrying.
thanks.

**Comment by CyberPunkMetalHead** [comment]
Can you increase the time to 60 seconds in line 220 and try again? `async with session.get(feed, headers=headers, timeout=7) as response:`

**Comment by OdinLin** [comment]
`session.get(feed, headers=headers, timeout=7, verify_ssl=False) as response` work for me

**Comment by simin75simin** [comment]
thanks for the potential fixes. using google colab (i need to use a proxy for binance and everything but binance's ordering system i.e. sockets apparently does not hook up with the proxy i set up when i initialize the client. see: https://github.com/sammchardy/python-binance/issues/248#issuecomment-451898555) here's what i got:
while none of those fixes gets me through every site, i find a combination of them work better, leaving out only six sites or so. 
what the program reads affects its trading behavior.
every fix alone works better than no fix.
