### ISSUE TITLE
Program freezes when order is timed out.

### ISSUE THREAD

**Issue by manosbagakis** [CyberPunkMetalHead/Binance-News-Sentiment-Bot#4]
preparing to buy BTC with 0.001829 USDT at 54668.42000000

binance.exceptions.BinanceAPIException: APIError(code=-1021): Timestamp for this request is outside of the recvWindow.

Code freeses when order is timed out.
Suggesting adding a continue statement when:
BinanceAPIException raises
BinanceOrderException raises

**Comment by CyberPunkMetalHead** [comment]
This should now be resolved with the last commit.
