### ISSUE TITLE
No module named 'binance.websockets'

### ISSUE THREAD

**Issue by RSolterman88** [CyberPunkMetalHead/Binance-News-Sentiment-Bot#54]
Hi, first of all thank you very much for your work!
I have tried to set up the bot, I installed everything and modified the settings in the console but I get this error when I try to run the bot:

root@vultr:~/Binance-News-Sentiment-Bot# python3 -m news-analysis
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/Binance-News-Sentiment-Bot/news-analysis.py", line 34, in <module>
    from binance.websockets import BinanceSocketManager
ModuleNotFoundError: No module named 'binance.websockets'

sWhat do you suggest I do? Thanks in advance

**Comment by danyeah** [comment]
I'm having the same issue.

**Comment by jmcl09** [comment]
Same here, the same issue , and 5 days ago it worked, but now ModuleNotFound

**Comment by hahnstep** [comment]
conda list | grep binance
# packages in environment at /home/stepain/miniconda3/envs/binancebot:
python-binance            0.7.10                   pypi_0    pypi

 python news-analysis.py
Press Ctrl-Q to stop the script
Bitcoin Price Weekly Update: 3rd May – 9th May 2021
WallStreetBets launches blockchain-powered app to decentralize indices
Visa Sees Bitcoin as Digital Gold | This Week in Crypto – May 3, 2021
.......

pip install python-binance --upgrade

conda list | grep binance
# packages in environment at /home/stepain/miniconda3/envs/binancebot:
python-binance            1.0.4                    pypi_0    pypi

python news-analysis.py
Traceback (most recent call last):
  File "news-analysis.py", line 36, in <module>
    from binance.websockets import BinanceSocketManager
ModuleNotFoundError: No module named 'binance.websockets'

i hope it helps.

**Comment by KrSuma** [comment]
https://github.com/sammchardy/python-binance/issues/170
seems like its inoperational

**Comment by CyberPunkMetalHead** [comment]
Looks like the Binance Websockets were down. I'll check on my side to see if the issue is resolved and will post and update.

**Comment by satanasov** [comment]
Hello there,

Is it possible this is related to python-binance package upgrade over 1.0.0+

I'm referring to this in their description:

https://github.com/sammchardy/python-binance#upgrading-to-v100

**Comment by CyberPunkMetalHead** [comment]
Yes, I'm currently running 0.7.1 and that's why I haven't been able to replicate the issue. 0.7.1 needs to be installed on your machine in order for this script to work. I will upgrade to 1.0.0 once that version is more stable :)
