### ISSUE TITLE
BCHUSDT Error for Binance API

### ISSUE THREAD

**Issue by CyberPunkMetalHead** [CyberPunkMetalHead/Binance-News-Sentiment-Bot#8]
Looks like the Binance API is returning a Symbol error when trying to place a trade on BCHUSD via the testnet. If anyone has encountered this issue before and has a workaround, please let me know.

**Comment by rohilrg** [comment]
Yes, me too for some reason, XLMUSDT is not working, even VETUSDT also.

**Comment by rohilrg** [comment]
I got the reason, because this a testnet api, they have limited pairs:
 ```[{'symbol': 'BNBBUSD', 'price': '603.00000000'}, {'symbol': 'BTCBUSD', 'price': '19000.00000000'}, {'symbol': 'ETHBUSD', 'price': '712.32000000'}, {'symbol': 'LTCBUSD', 'price': '265.54000000'}, {'symbol': 'TRXBUSD', 'price': '0.05500000'}, {'symbol': 'XRPBUSD', 'price': '1.75000000'}, {'symbol': 'BNBUSDT', 'price': '445.05000000'}, {'symbol': 'BTCUSDT', 'price': '20000.00000000'}, {'symbol': 'ETHUSDT', 'price': '909.00000000'}, {'symbol': 'LTCUSDT', 'price': '97.81000000'}, {'symbol': 'TRXUSDT', 'price': '0.10056000'}, {'symbol': 'XRPUSDT', 'price': '1.77815000'}, {'symbol': 'BNBBTC', 'price': '0.01000000'}, {'symbol': 'ETHBTC', 'price': '0.60154000'}, {'symbol': 'LTCBTC', 'price': '0.00700000'}, {'symbol': 'TRXBTC', 'price': '0.00006000'}, {'symbol': 'XRPBTC', 'price': '0.00001700'}, {'symbol': 'LTCBNB', 'price': '0.50000000'}, {'symbol': 'TRXBNB', 'price': '0.00036200'}, {'symbol': 'XRPBNB', 'price': '0.00071000'}]```

**Comment by CyberPunkMetalHead** [comment]
Awesome, thanks for that!
